[package]
name = "voting"
version = "0.0.1"

[addresses]
test = "_"
# Define the address aliases used in the project
[dev-addresses]
test = "0x9000"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }